language: ruby
rvm:
  - 2.6.6

script:
  - bundle exec rake db:create:all
  - bundle exec rake db:migrate RAILS_ENV=test
  - ruby -Itest test/models/article_test.rb
  - ruby -Itest test/models/comment_test.rb
  - ruby -S bundle exec cucumber --profile default

services:
  - sqlite3